name: Tan Hong Kai Workflow

on:
  push:
    branches:
      - main
      
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello Mr Ngui or anyone seeing this, my name is Hong Kai"
